from ROOT import TFile, TCanvas, TLegend,TH1F, TPaveText
from cpyroot.tools.tdrstyle import setTDRStyle

setTDRStyle()

fraw = TFile('/data/gtouquet/samples_root/plots/outfilerawpt.root')
frec = TFile('/data/gtouquet/samples_root/plots/outfilerecopt.root')
frecnn = TFile('/data/gtouquet/samples_root/plots/outfilept_rec.root')

respraw = fraw.Get('resphist')
resprec = frec.Get('resphist')
resprecnn = frecnn.Get('resphist')

can = TCanvas()
supphist = TH1F("supphist","",40,60,320)
supphist.GetYaxis().SetRangeUser(0.9,1.05)
supphist.GetYaxis().SetTitle('Response')
supphist.GetXaxis().SetTitle('p_{T} gen')
supphist.SetStats(0)
supphist.Draw()
respraw.SetMarkerColor(4)
respraw.SetMarkerStyle(20)
respraw.SetMarkerSize(1)
respraw.Draw("same pl")
resprec.SetMarkerColor(2)
resprec.SetMarkerStyle(20)
resprec.SetMarkerSize(1)
resprec.Draw("same pl")
resprecnn.SetMarkerColor(3)
resprecnn.SetMarkerStyle(20)
resprecnn.SetMarkerSize(1)
resprecnn.Draw("same pl")
legend = TLegend(0.7,0.8,0.9,0.9)
legend.AddEntry(respraw,'RawJet',"pl")
legend.AddEntry(resprec,'RecoJet',"pl")
legend.AddEntry(resprecnn,'Recnn Jet',"pl")
legend.Draw('same')
text = TPaveText(0.2,0.7,0.7,0.9,'NDC')
text.SetFillStyle(3000)
text.AddText('cuts applied at gen and reco level:')
text.AddText('\eta < 1.3')
text.AddText('p_{T} > 60.')
text.Draw("same")

can.SaveAs('data/plots/responses.pdf')

fraw = TFile('/data/gtouquet/samples_root/plots/outfilerawpt.root')
frec = TFile('/data/gtouquet/samples_root/plots/outfilerecopt.root')
frecnn = TFile('/data/gtouquet/samples_root/plots/outfilept_rec.root')

respraw = fraw.Get('reshist')
resprec = frec.Get('reshist')
resprecnn = frecnn.Get('reshist')

can = TCanvas()
supphist = TH1F("supphist","",40,60,320)
supphist.GetYaxis().SetRangeUser(0.05,0.12)
supphist.GetYaxis().SetTitle('Resolution')
supphist.GetXaxis().SetTitle('p_{T} gen')
supphist.SetStats(0)
supphist.Draw()
respraw.SetMarkerColor(4)
respraw.SetMarkerStyle(20)
respraw.SetMarkerSize(1)
respraw.Draw("same pl")
resprec.SetMarkerColor(2)
resprec.SetMarkerStyle(20)
resprec.SetMarkerSize(1)
resprec.Draw("same pl")
resprecnn.SetMarkerColor(3)
resprecnn.SetMarkerStyle(20)
resprecnn.SetMarkerSize(1)
resprecnn.Draw("same pl")
legend = TLegend(0.7,0.8,0.9,0.9)
legend.AddEntry(respraw,'RawJet',"pl")
legend.AddEntry(resprec,'RecoJet',"pl")
legend.AddEntry(resprecnn,'Recnn Jet',"pl")
legend.Draw('same')
text = TPaveText(0.2,0.7,0.7,0.9,'NDC')
text.SetFillStyle(3000)
text.AddText('cuts applied at gen and reco level:')
text.AddText('\eta < 1.3')
text.AddText('p_{T} > 60.')
text.Draw("same")

can.SaveAs('data/plots/resolutions.pdf')

###eta plots

fraw = TFile('/data/gtouquet/samples_root/plots/outfilerawpt_eta.root')
frec = TFile('/data/gtouquet/samples_root/plots/outfilerecopt_eta.root')
frecnn = TFile('/data/gtouquet/samples_root/plots/outfilept_rec_eta.root')

respraw = fraw.Get('resphist')
resprec = frec.Get('resphist')
resprecnn = frecnn.Get('resphist')

can = TCanvas()
supphist = TH1F("supphist","",40,0.,1.3)
supphist.GetYaxis().SetRangeUser(0.9,1.05)
supphist.GetYaxis().SetTitle('Response')
supphist.GetXaxis().SetTitle('\eta gen')
supphist.SetStats(0)
supphist.Draw()
respraw.SetMarkerColor(4)
respraw.SetMarkerStyle(20)
respraw.SetMarkerSize(1)
respraw.Draw("same pl")
resprec.SetMarkerColor(2)
resprec.SetMarkerStyle(20)
resprec.SetMarkerSize(1)
resprec.Draw("same pl")
resprecnn.SetMarkerColor(3)
resprecnn.SetMarkerStyle(20)
resprecnn.SetMarkerSize(1)
resprecnn.Draw("same pl")
legend = TLegend(0.7,0.8,0.9,0.9)
legend.AddEntry(respraw,'RawJet',"pl")
legend.AddEntry(resprec,'RecoJet',"pl")
legend.AddEntry(resprecnn,'Recnn Jet',"pl")
legend.Draw('same')
text = TPaveText(0.2,0.7,0.7,0.9,'NDC')
text.SetFillStyle(3000)
text.AddText('150 < p_{T} < 200')
text.Draw("same")

can.SaveAs('data/plots/responses_eta.pdf')

fraw = TFile('/data/gtouquet/samples_root/plots/outfilerawpt_eta.root')
frec = TFile('/data/gtouquet/samples_root/plots/outfilerecopt_eta.root')
frecnn = TFile('/data/gtouquet/samples_root/plots/outfilept_rec_eta.root')

respraw = fraw.Get('reshist')
resprec = frec.Get('reshist')
resprecnn = frecnn.Get('reshist')

can = TCanvas()
supphist = TH1F("supphist","",40,0.,1.3)
supphist.GetYaxis().SetRangeUser(0.05,0.12)
supphist.GetYaxis().SetTitle('Resolution')
supphist.GetXaxis().SetTitle('\eta gen')
supphist.SetStats(0)
supphist.Draw()
respraw.SetMarkerColor(4)
respraw.SetMarkerStyle(20)
respraw.SetMarkerSize(1)
respraw.Draw("same pl")
resprec.SetMarkerColor(2)
resprec.SetMarkerStyle(20)
resprec.SetMarkerSize(1)
resprec.Draw("same pl")
resprecnn.SetMarkerColor(3)
resprecnn.SetMarkerStyle(20)
resprecnn.SetMarkerSize(1)
resprecnn.Draw("same pl")
legend = TLegend(0.7,0.8,0.9,0.9)
legend.AddEntry(respraw,'RawJet',"pl")
legend.AddEntry(resprec,'RecoJet',"pl")
legend.AddEntry(resprecnn,'Recnn Jet',"pl")
legend.Draw('same')
text = TPaveText(0.2,0.7,0.7,0.9,'NDC')
text.SetFillStyle(3000)
text.AddText('150 < p_{T} < 200')
text.Draw("same")

can.SaveAs('data/plots/resolutions_eta.pdf')
